name: flutter_clean_code
description: Esuto de clean code em flutter.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Biblioteca de testes do Dart (para não precisa do Flutter)
  test: 1.15.0 
  # Mock de classes
  mockito: 3.0.2
  # Gerar valores aleatórios em testes
  faker: 1.3.0
 
flutter:
  uses-material-design: true